/*
Counts total patients in each province
*/

SELECT
	PR.PROVINCE_NAME,
	COUNT(P.PATIENT_ID) AS TOTAL_PATIENTS
FROM
	PROVINCES PR
	JOIN PATIENTS P ON PR.PROVINCE_ID = P.PROVINCE_ID
GROUP BY
	PR.PROVINCE_NAME
ORDER BY
	TOTAL_PATIENTS DESC;